sudo: required

language: java

services:
  - mysql
  - docker

env:
  global:
    - MYSQL_PWD=root
    - REGISTRY_USER=cxy1221
    - REGISTRY_PWD=ccxxyy217991
before_install:
  - sudo service mysql restart
  - sudo docker pull cxy1221/sshlogin_tomcat
  - sudo docker run -d --network="host" cxy1221/sshlogin_tomcat



before_deploy:
  - sudo docker login -u "$REGISTRY_USER" -p "$REGISTRY_PWD"

deploy:
  provider: script
  script: sudo docker push cxy1221/sshlogin_tomcat
  on:
branch: master
