sudo: required

language: java

jdk:
  - openjdk11

services:
  - mysql
  - docker

env:
  global:
    - MYSQL_PWD=root
    - REGISTRY_USER=cxy1221
    - REGISTRY_PWD=ccxxyy217991
before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -u root --password="root" 
  - sudo service mysql restart
  - sudo docker pull cxy1221/sshlogin_tomcat
  - sudo docker run -d --network="host" cxy1221/sshlogin_tomcat



before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PWD"

deploy:
  provider: script
  script: docker push cxy1221/sshlogin_tomcat
  on:
branch: master
